# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_winmain.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(870, 582)
        Form.setMaximumSize(QtCore.QSize(1000, 1000))
        Form.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.ButtonAbrir = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonAbrir.sizePolicy().hasHeightForWidth())
        self.ButtonAbrir.setSizePolicy(sizePolicy)
        self.ButtonAbrir.setMinimumSize(QtCore.QSize(54, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonAbrir.setFont(font)
        self.ButtonAbrir.setCheckable(False)
        self.ButtonAbrir.setAutoRepeat(False)
        self.ButtonAbrir.setDefault(True)
        self.ButtonAbrir.setFlat(True)
        self.ButtonAbrir.setObjectName("ButtonAbrir")
        self.gridLayout.addWidget(self.ButtonAbrir, 0, 0, 2, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BtnPClave = QtWidgets.QPushButton(self.tab)
        self.BtnPClave.setObjectName("BtnPClave")
        self.gridLayout_2.addWidget(self.BtnPClave, 0, 2, 1, 1)
        self.BtnGenerar = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.BtnGenerar.setFont(font)
        self.BtnGenerar.setObjectName("BtnGenerar")
        self.gridLayout_2.addWidget(self.BtnGenerar, 0, 7, 1, 1)
        self.FiltrarPalabra = QtWidgets.QLineEdit(self.tab)
        self.FiltrarPalabra.setText("")
        self.FiltrarPalabra.setObjectName("FiltrarPalabra")
        self.gridLayout_2.addWidget(self.FiltrarPalabra, 0, 1, 1, 1)
        self.BtnGuardar = QtWidgets.QPushButton(self.tab)
        self.BtnGuardar.setObjectName("BtnGuardar")
        self.gridLayout_2.addWidget(self.BtnGuardar, 0, 8, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 11, 1, 1)
        self.BtnWordCloud = QtWidgets.QPushButton(self.tab)
        self.BtnWordCloud.setObjectName("BtnWordCloud")
        self.gridLayout_2.addWidget(self.BtnWordCloud, 0, 9, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 0, 5, 1, 2)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 4, 1, 1)
        self.BtnHistograma = QtWidgets.QPushButton(self.tab)
        self.BtnHistograma.setObjectName("BtnHistograma")
        self.gridLayout_2.addWidget(self.BtnHistograma, 0, 10, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formGroupBox = QtWidgets.QGroupBox(self.tab_2)
        self.formGroupBox.setGeometry(QtCore.QRect(0, 0, 251, 411))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.BtnEntrenar = QtWidgets.QPushButton(self.formGroupBox)
        self.BtnEntrenar.setObjectName("BtnEntrenar")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.BtnEntrenar)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.BtnEnviar = QtWidgets.QPushButton(self.formGroupBox)
        self.BtnEnviar.setObjectName("BtnEnviar")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.BtnEnviar)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditAns = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEditAns.setObjectName("lineEditAns")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEditAns)
        self.checkBoxAmigos = QtWidgets.QCheckBox(self.formGroupBox)
        self.checkBoxAmigos.setObjectName("checkBoxAmigos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxAmigos)
        self.checkBoxFamilia = QtWidgets.QCheckBox(self.formGroupBox)
        self.checkBoxFamilia.setObjectName("checkBoxFamilia")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxFamilia)
        self.checkBoxFiesta = QtWidgets.QCheckBox(self.formGroupBox)
        self.checkBoxFiesta.setObjectName("checkBoxFiesta")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBoxFiesta)
        self.checkBoxHogar = QtWidgets.QCheckBox(self.formGroupBox)
        self.checkBoxHogar.setObjectName("checkBoxHogar")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBoxHogar)
        self.checkBoxGames = QtWidgets.QCheckBox(self.formGroupBox)
        self.checkBoxGames.setObjectName("checkBoxGames")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBoxGames)
        self.checkBoxPlaya = QtWidgets.QCheckBox(self.formGroupBox)
        self.checkBoxPlaya.setObjectName("checkBoxPlaya")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBoxPlaya)
        self.checkBoxVacaciones = QtWidgets.QCheckBox(self.formGroupBox)
        self.checkBoxVacaciones.setObjectName("checkBoxVacaciones")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.checkBoxVacaciones)
        self.checkBoxVerano = QtWidgets.QCheckBox(self.formGroupBox)
        self.checkBoxVerano.setObjectName("checkBoxVerano")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.checkBoxVerano)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ButtonAbrir.setText(_translate("Form", "Abrir archivo"))
        self.BtnPClave.setText(_translate("Form", "Buscar"))
        self.BtnGenerar.setText(_translate("Form", "Generar"))
        self.BtnGuardar.setText(_translate("Form", "Guardar"))
        self.BtnWordCloud.setText(_translate("Form", "WordCloud"))
        self.label.setText(_translate("Form", "Columnas"))
        self.BtnHistograma.setText(_translate("Form", "Histograma"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Base de datos reducida"))
        self.BtnEntrenar.setText(_translate("Form", "Entrenar"))
        self.label_3.setText(_translate("Form", "Palabras Clave"))
        self.BtnEnviar.setText(_translate("Form", "Enviar"))
        self.label_2.setText(_translate("Form", "Repuesta"))
        self.checkBoxAmigos.setText(_translate("Form", "Amigos"))
        self.checkBoxFamilia.setText(_translate("Form", "Familia"))
        self.checkBoxFiesta.setText(_translate("Form", "Fiesta"))
        self.checkBoxHogar.setText(_translate("Form", "Hogar"))
        self.checkBoxGames.setText(_translate("Form", "Games"))
        self.checkBoxPlaya.setText(_translate("Form", "Playa"))
        self.checkBoxVacaciones.setText(_translate("Form", "Vacaciones"))
        self.checkBoxVerano.setText(_translate("Form", "Verano"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Red Neuronal"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

